version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
      minor-and-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
